import json

keys = {
    "feature1_title": "Multi-Angle Face Capture",
    "feature1_desc": "Register your face from 4 angles for precise, secure recognition that works from any position.",
    "feature2_title": "Liveness Detection",
    "feature2_desc": "Anti-spoofing technology detects photos and videos, ensuring only real persons can authenticate.",
    "feature3_title": "Encrypted Embeddings",
    "feature3_desc": "Face data is stored as encrypted mathematical vectors — never as images. Privacy by design.",
    "feature4_title": "Real-Time Verification",
    "feature4_desc": "Face matching happens in under 2 seconds using optimized AI models for instant access.",
    "feature5_title": "JWT Authentication",
    "feature5_desc": "Industry-standard JSON Web Tokens with automatic refresh and secure session management.",
    "feature6_title": "Mobile Responsive",
    "feature6_desc": "Works seamlessly on phones, tablets, and laptops. Camera adapts to any device automatically.",
    
    "attendance_title": "Real-time Attendance System",
    "attendance_live": "Live:",
    "attendance_in": "Attendance In",
    "attendance_out": "Attendance Out",
    "scan_in_title": "Scan QR to Login",
    "scan_out_title": "Scan QR to Logout",
    "scan_instruction": "Align QR code within the frame",
    "close": "Close",
    "logs_title": "Today's Logs",
    "search_placeholder": "Search by name or ID...",
    "tab_today": "Today's Logs",
    "tab_consolidated": "Consolidated",
    "tab_details": "Details",
    "status_in": "In Office",
    "status_out": "Logged Out",
    "status_absent": "Absent",
    "table_name": "Name",
    "table_id": "Emp ID",
    "table_dept": "Dept",
    "table_in": "In Time",
    "table_out": "Out Time",
    "table_status": "Status",

    "kiosk_title": "Office Logout Kiosk",
    "kiosk_desc": "For high security, you must scan your identity QR and verify your face to log out of the office.",
    "kiosk_scan": "Scan Identity QR",
    "kiosk_cancel": "Back",
    "employee_details": "Employee Details",
    "name": "Name:",
    "emp_id": "Employee ID:",
    "dept": "Department:",
    "login_time": "Login Time:",
    "current_time": "Current Time:",
    "working_hours": "Working Hours:",
    "proceed_face": "Proceed to Face Verification",
    "verifying": "Verifying...",

    "admin_title": "Admin Control Panel",
    "admin_subtitle": "Configure global company settings for all employees",
    "logged_in_as": "Logged in as",
    "tab_settings": "Company Settings",
    "office_hours": "Office Working Hours",
    "office_hours_desc": "This sets the mandatory working hours for ALL employees. The Logout Kiosk will block employees from leaving before completing these hours.",
    "hours_day": "Hours Per Day",
    "hours_week": "Hours Per Week",
    "hours_month": "Hours Per Month",
    "hours_year": "Hours Per Year",
    "weekly_off": "Weekly Off Day",
    "save_settings": "Save Settings",
    
    "dashboard": "Dashboard",
    "locations": "Locations",
    "admin": "Admin Panel",
    "attendance": "Attendance System",
    "kiosk": "Logout Kiosk",
    "login": "Login",
    "register": "Register",
    "logout": "Logout",
    "settings": "Settings",
    "profile": "Profile",
    "language": "Language",
    "home_badge": "Powered by AI Face Recognition",
    "home_title": "Secure Authentication",
    "home_subtitle": "with Face Recognition",
    "home_desc": "A production-ready authentication system that combines traditional password security with advanced AI-powered face recognition for unbeatable account protection.",
    "home_get_started": "Get Started",
    "home_sign_in": "Sign In"
}

# Simplified translations (I will populate this with accurate translations)
translations = {
    "en": keys,
    "kn": {
        "feature1_title": "ಬಹು-ಕೋನ ಮುಖ ಸೆರೆಹಿಡಿಯುವಿಕೆ",
        "feature1_desc": "ಯಾವುದೇ ಸ್ಥಾನದಿಂದ ಕೆಲಸ ಮಾಡುವ ನಿಖರವಾದ, ಸುರಕ್ಷಿತ ಗುರುತಿಸುವಿಕೆಗಾಗಿ 4 ಕೋನಗಳಿಂದ ನಿಮ್ಮ ಮುಖವನ್ನು ನೋಂದಾಯಿಸಿ.",
        "feature2_title": "ಲೈವ್ನೆಸ್ ಪತ್ತೆ",
        "feature2_desc": "ಆಂಟಿ-ಸ್ಪೂಫಿಂಗ್ ತಂತ್ರಜ್ಞಾನವು ಫೋಟೋಗಳು ಮತ್ತು ವೀಡಿಯೊಗಳನ್ನು ಪತ್ತೆ ಮಾಡುತ್ತದೆ, ನೈಜ ವ್ಯಕ್ತಿಗಳು ಮಾತ್ರ ದೃಢೀಕರಿಸಬಹುದು ಎಂದು ಖಚಿತಪಡಿಸುತ್ತದೆ.",
        "feature3_title": "ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾದ ಎಂಬೆಡಿಂಗ್‌ಗಳು",
        "feature3_desc": "ಮುಖದ ಡೇಟಾವನ್ನು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಿದ ಗಣಿತದ ವಾಹಕಗಳಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ - ಎಂದಿಗೂ ಚಿತ್ರಗಳಂತೆ ಅಲ್ಲ. ವಿನ್ಯಾಸದಿಂದ ಗೌಪ್ಯತೆ.",
        "feature4_title": "ನೈಜ-ಸಮಯದ ಪರಿಶೀಲನೆ",
        "feature4_desc": "ತ್ವರಿತ ಪ್ರವೇಶಕ್ಕಾಗಿ ಆಪ್ಟಿಮೈಸ್ಡ್ AI ಮಾದರಿಗಳನ್ನು ಬಳಸಿಕೊಂಡು ಮುಖದ ಹೊಂದಾಣಿಕೆಯು 2 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ನಡೆಯುತ್ತದೆ.",
        "feature5_title": "JWT ದೃಢೀಕರಣ",
        "feature5_desc": "ಸ್ವಯಂಚಾಲಿತ ರಿಫ್ರೆಶ್ ಮತ್ತು ಸುರಕ್ಷಿತ ಅಧಿವೇಶನ ನಿರ್ವಹಣೆಯೊಂದಿಗೆ ಉದ್ಯಮ-ಗುಣಮಟ್ಟದ JSON ವೆಬ್ ಟೋಕನ್‌ಗಳು.",
        "feature6_title": "ಮೊಬೈಲ್ ರೆಸ್ಪಾನ್ಸಿವ್",
        "feature6_desc": "ಫೋನ್‌ಗಳು, ಟ್ಯಾಬ್ಲೆಟ್‌ಗಳು ಮತ್ತು ಲ್ಯಾಪ್‌ಟಾಪ್‌ಗಳಲ್ಲಿ ಮನಬಂದಂತೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ. ಕ್ಯಾಮೆರಾ ಯಾವುದೇ ಸಾಧನಕ್ಕೆ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ.",
        "attendance_title": "ನೈಜ-ಸಮಯದ ಹಾಜರಾತಿ ವ್ಯವಸ್ಥೆ",
        "attendance_live": "ಲೈವ್:",
        "attendance_in": "ಹಾಜರಾತಿ ಪ್ರವೇಶ",
        "attendance_out": "ಹಾಜರಾತಿ ನಿರ್ಗಮನ",
        "scan_in_title": "ಲಾಗಿನ್ ಮಾಡಲು ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        "scan_out_title": "ಲಾಗ್‌ಔಟ್ ಮಾಡಲು ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        "scan_instruction": "ಫ್ರೇಮ್ ಒಳಗೆ QR ಕೋಡ್ ಅನ್ನು ಹೊಂದಿಸಿ",
        "close": "ಮುಚ್ಚಿ",
        "logs_title": "ಇಂದಿನ ದಾಖಲೆಗಳು",
        "search_placeholder": "ಹೆಸರು ಅಥವಾ ಐಡಿಯಿಂದ ಹುಡುಕಿ...",
        "tab_today": "ಇಂದಿನ ದಾಖಲೆಗಳು",
        "tab_consolidated": "ಏಕೀಕೃತ",
        "tab_details": "ವಿವರಗಳು",
        "status_in": "ಕಚೇರಿಯಲ್ಲಿ",
        "status_out": "ಲಾಗ್ ಔಟ್ ಆಗಿದೆ",
        "status_absent": "ಗೈರು",
        "table_name": "ಹೆಸರು",
        "table_id": "ಉದ್ಯೋಗಿ ಐಡಿ",
        "table_dept": "ಇಲಾಖೆ",
        "table_in": "ಪ್ರವೇಶ ಸಮಯ",
        "table_out": "ನಿರ್ಗಮನ ಸಮಯ",
        "table_status": "ಸ್ಥಿತಿ",
        "kiosk_title": "ಕಚೇರಿ ಲಾಗ್‌ಔಟ್ ಕಿಯೋಸ್ಕ್",
        "kiosk_desc": "ಹೆಚ್ಚಿನ ಭದ್ರತೆಗಾಗಿ, ಕಚೇರಿಯಿಂದ ಲಾಗ್‌ಔಟ್ ಮಾಡಲು ನಿಮ್ಮ ಗುರುತಿನ ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಮುಖವನ್ನು ಪರಿಶೀಲಿಸಬೇಕು.",
        "kiosk_scan": "ಗುರುತಿನ QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        "kiosk_cancel": "ಹಿಂದೆ",
        "employee_details": "ಉದ್ಯೋಗಿ ವಿವರಗಳು",
        "name": "ಹೆಸರು:",
        "emp_id": "ಉದ್ಯೋಗಿ ಐಡಿ:",
        "dept": "ಇಲಾಖೆ:",
        "login_time": "ಲಾಗಿನ್ ಸಮಯ:",
        "current_time": "ಪ್ರಸ್ತುತ ಸಮಯ:",
        "working_hours": "ಕೆಲಸದ ಸಮಯ:",
        "proceed_face": "ಮುಖ ಪರಿಶೀಲನೆಗೆ ಮುಂದುವರಿಯಿರಿ",
        "verifying": "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
        "admin_title": "ಆಡಳಿತ ನಿಯಂತ್ರಣ ಫಲಕ",
        "admin_subtitle": "ಎಲ್ಲಾ ಉದ್ಯೋಗಿಗಳಿಗೆ ಜಾಗತಿಕ ಕಚೇರಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಿ",
        "logged_in_as": "ಲಾಗಿನ್ ಆಗಿದ್ದಾರೆ",
        "tab_settings": "ಕಂಪನಿ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "office_hours": "ಕಚೇರಿ ಕೆಲಸದ ಸಮಯ",
        "office_hours_desc": "ಇದು ಎಲ್ಲಾ ಉದ್ಯೋಗಿಗಳಿಗೆ ಕಡ್ಡಾಯ ಕೆಲಸದ ಸಮಯವನ್ನು ಹೊಂದಿಸುತ್ತದೆ. ಈ ಸಮಯವನ್ನು ಪೂರ್ಣಗೊಳಿಸುವ ಮೊದಲು ಲಾಗ್‌ಔಟ್ ಕಿಯೋಸ್ಕ್ ಉದ್ಯೋಗಿಗಳನ್ನು ತಡೆಯುತ್ತದೆ.",
        "hours_day": "ದಿನಕ್ಕೆ ಗಂಟೆಗಳು",
        "hours_week": "ವಾರಕ್ಕೆ ಗಂಟೆಗಳು",
        "hours_month": "ತಿಂಗಳಿಗೆ ಗಂಟೆಗಳು",
        "hours_year": "ವರ್ಷಕ್ಕೆ ಗಂಟೆಗಳು",
        "weekly_off": "ವಾರದ ರಜೆ ದಿನ",
        "save_settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ",
        "dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "locations": "ಸ್ಥಳಗಳು",
        "admin": "ಆಡಳಿತ ಮಂಡಳಿ",
        "attendance": "ಹಾಜರಾತಿ ವ್ಯವಸ್ಥೆ",
        "kiosk": "ಲಾಗ್ ಔಟ್ ಕಿಯೋಸ್ಕ್",
        "login": "ಲಾಗಿನ್",
        "register": "ನೋಂದಾಯಿಸಿ",
        "logout": "ಲಾಗ್ ಔಟ್",
        "settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "profile": "ಪ್ರೊಫೈಲ್",
        "language": "ಭಾಷೆ",
        "home_badge": "AI ಮುಖ ಗುರುತಿಸುವಿಕೆ",
        "home_title": "ಸುರಕ್ಷಿತ ದೃಢೀಕರಣ",
        "home_subtitle": "ಮುಖ ಗುರುತಿಸುವಿಕೆಯೊಂದಿಗೆ",
        "home_desc": "ಸಾಂಪ್ರದಾಯಿಕ ಪಾಸ್‌ವರ್ಡ್ ಭದ್ರತೆಯನ್ನು ಸುಧಾರಿತ ಎಐ-ಚಾಲಿತ ಮುಖ ಗುರುತಿಸುವಿಕೆಯೊಂದಿಗೆ ಸಂಯೋಜಿಸುವ ಉತ್ತಮ ದೃಢೀಕರಣ ವ್ಯವಸ್ಥೆ.",
        "home_get_started": "ಪ್ರಾರಂಭಿಸಿ",
        "home_sign_in": "ಸೈನ್ ಇನ್"
    },
    "hi": {
        "feature1_title": "मल्टी-एंगल फेस कैप्चर",
        "feature1_desc": "सटीक और सुरक्षित पहचान के लिए अपने चेहरे को 4 कोणों से पंजीकृत करें जो किसी भी स्थिति से काम करता है।",
        "feature2_title": "लाइवनेस डिटेक्शन",
        "feature2_desc": "एंटी-स्पूफिंग तकनीक फ़ोटो और वीडियो का पता लगाती है, यह सुनिश्चित करते हुए कि केवल वास्तविक व्यक्ति ही प्रमाणित कर सकें।",
        "feature3_title": "एन्क्रिप्टेड एम्बेडिंग",
        "feature3_desc": "चेहरे का डेटा एन्क्रिप्टेड गणितीय वैक्टर के रूप में संग्रहीत किया जाता है - कभी छवियों के रूप में नहीं। डिज़ाइन द्वारा गोपनीयता।",
        "feature4_title": "रियल-टाइम सत्यापन",
        "feature4_desc": "त्वरित पहुँच के लिए अनुकूलित AI मॉडल का उपयोग करके चेहरे का मिलान 2 सेकंड के भीतर होता है।",
        "feature5_title": "JWT प्रमाणीकरण",
        "feature5_desc": "स्वचालित रिफ्रेश और सुरक्षित सत्र प्रबंधन के साथ उद्योग-मानक JSON वेब टोकन।",
        "feature6_title": "मोबाइल रिस्पॉन्सिव",
        "feature6_desc": "फोन, टैबलेट और लैपटॉप पर निर्बाध रूप से काम करता है। कैमरा स्वचालित रूप से किसी भी डिवाइस के अनुकूल हो जाता है।",
        "attendance_title": "रीयल-टाइम उपस्थिति प्रणाली",
        "attendance_live": "लाइव:",
        "attendance_in": "उपस्थिति दर्ज (इन)",
        "attendance_out": "उपस्थिति दर्ज (आउट)",
        "scan_in_title": "लॉगिन के लिए क्यूआर स्कैन करें",
        "scan_out_title": "लॉगआउट के लिए क्यूआर स्कैन करें",
        "scan_instruction": "क्यूआर कोड को फ्रेम के भीतर संरेखित करें",
        "close": "बंद करें",
        "logs_title": "आज के लॉग",
        "search_placeholder": "नाम या आईडी से खोजें...",
        "tab_today": "आज के लॉग",
        "tab_consolidated": "समेकित",
        "tab_details": "विवरण",
        "status_in": "कार्यालय में",
        "status_out": "लॉग आउट",
        "status_absent": "अनुपस्थित",
        "table_name": "नाम",
        "table_id": "कर्मचारी आईडी",
        "table_dept": "विभाग",
        "table_in": "इन समय",
        "table_out": "आउट समय",
        "table_status": "स्थिति",
        "kiosk_title": "कार्यालय लॉगआउट कियोस्क",
        "kiosk_desc": "उच्च सुरक्षा के लिए, कार्यालय से लॉगआउट करने के लिए आपको अपनी पहचान क्यूआर को स्कैन करना होगा और अपने चेहरे को सत्यापित करना होगा।",
        "kiosk_scan": "पहचान क्यूआर स्कैन करें",
        "kiosk_cancel": "वापस",
        "employee_details": "कर्मचारी विवरण",
        "name": "नाम:",
        "emp_id": "कर्मचारी आईडी:",
        "dept": "विभाग:",
        "login_time": "लॉगिन समय:",
        "current_time": "वर्तमान समय:",
        "working_hours": "काम के घंटे:",
        "proceed_face": "चेहरा सत्यापन के लिए आगे बढ़ें",
        "verifying": "सत्यापन किया जा रहा है...",
        "admin_title": "प्रशासन नियंत्रण कक्ष",
        "admin_subtitle": "सभी कर्मचारियों के लिए वैश्विक कंपनी सेटिंग्स कॉन्फ़िगर करें",
        "logged_in_as": "लॉग इन हैं:",
        "tab_settings": "कंपनी सेटिंग्स",
        "office_hours": "कार्यालय काम के घंटे",
        "office_hours_desc": "यह सभी कर्मचारियों के लिए अनिवार्य काम के घंटे निर्धारित करता है। लॉगआउट कियोस्क कर्मचारियों को इन घंटों को पूरा करने से पहले जाने से रोक देगा।",
        "hours_day": "घंटे प्रति दिन",
        "hours_week": "घंटे प्रति सप्ताह",
        "hours_month": "घंटे प्रति माह",
        "hours_year": "घंटे प्रति वर्ष",
        "weekly_off": "साप्ताहिक अवकाश का दिन",
        "save_settings": "सेटिंग्स सहेजें",
        "dashboard": "डैशबोर्ड",
        "locations": "स्थान",
        "admin": "व्यवस्थापक पैनल",
        "attendance": "उपस्थिति प्रणाली",
        "kiosk": "लॉगआउट कियोस्क",
        "login": "लॉगिन",
        "register": "पंजीकरण",
        "logout": "लॉग आउट",
        "settings": "सेटिंग्स",
        "profile": "प्रोफ़ाइल",
        "language": "भाषा",
        "home_badge": "AI चेहरा पहचान द्वारा संचालित",
        "home_title": "सुरक्षित प्रमाणीकरण",
        "home_subtitle": "चेहरा पहचान के साथ",
        "home_desc": "एक उत्पादन-तैयार प्रमाणीकरण प्रणाली जो पारंपरिक पासवर्ड सुरक्षा को उन्नत एआई-संचालित चेहरे की पहचान के साथ जोड़ती है।",
        "home_get_started": "शुरू करें",
        "home_sign_in": "साइन इन"
    },
    "bn": {
        "feature1_title": "মাল্টি-অ্যাঙ্গেল ফেস ক্যাপচার",
        "feature1_desc": "সঠিক, সুরক্ষিত স্বীকৃতির জন্য ৪টি কোণ থেকে আপনার মুখ নিবন্ধন করুন যা যেকোনো অবস্থান থেকে কাজ করে।",
        "feature2_title": "লাইভনেস ডিটেকশন",
        "feature2_desc": "অ্যান্টি-স্পুফিং প্রযুক্তি ফটো এবং ভিডিও শনাক্ত করে, নিশ্চিত করে যে শুধুমাত্র প্রকৃত ব্যক্তিরাই প্রমাণীকরণ করতে পারে।",
        "feature3_title": "এনক্রিপ্ট করা এম্বেডিং",
        "feature3_desc": "মুখের ডেটা এনক্রিপ্ট করা গাণিতিক ভেক্টর হিসাবে সংরক্ষণ করা হয় - কখনোই ছবি হিসাবে নয়। ডিজাইনের মাধ্যমে গোপনীয়তা।",
        "feature4_title": "রিয়েল-টাইম ভেরিফিকেশন",
        "feature4_desc": "তাত্ক্ষণিক অ্যাক্সেসের জন্য অপ্টিমাইজ করা এআই মডেলগুলি ব্যবহার করে ২ সেকেন্ডের মধ্যে ফেস ম্যাচিং ঘটে।",
        "feature5_title": "JWT প্রমাণীকরণ",
        "feature5_desc": "স্বয়ংক্রিয় রিফ্রেশ এবং সুরক্ষিত সেশন ম্যানেজমেন্ট সহ ইন্ডাস্ট্রি-স্ট্যান্ডার্ড JSON ওয়েব টোকেন।",
        "feature6_title": "মোবাইল রেসপন্সিভ",
        "feature6_desc": "ফোন, ট্যাবলেট এবং ল্যাপটপে নির্বিঘ্নে কাজ করে। ক্যামেরা স্বয়ংক্রিয়ভাবে যেকোনো ডিভাইসের সাথে খাপ খাইয়ে নেয়।",
        "attendance_title": "রিয়েল-টাইম উপস্থিতি সিস্টেম",
        "attendance_live": "লাইভ:",
        "attendance_in": "উপস্থিতি ইন",
        "attendance_out": "উপস্থিতি আউট",
        "scan_in_title": "লগইন করতে কিউআর স্ক্যান করুন",
        "scan_out_title": "লগআউট করতে কিউআর স্ক্যান করুন",
        "scan_instruction": "ফ্রেমের মধ্যে কিউআর কোড সারিবদ্ধ করুন",
        "close": "বন্ধ করুন",
        "logs_title": "আজকের লগ",
        "search_placeholder": "নাম বা আইডি দিয়ে অনুসন্ধান করুন...",
        "tab_today": "আজকের লগ",
        "tab_consolidated": "একত্রিত",
        "tab_details": "বিবরণ",
        "status_in": "অফিসে",
        "status_out": "লগ আউট",
        "status_absent": "অনুপস্থিত",
        "table_name": "নাম",
        "table_id": "কর্মী আইডি",
        "table_dept": "বিভাগ",
        "table_in": "ইন সময়",
        "table_out": "আউট সময়",
        "table_status": "স্ট্যাটাস",
        "kiosk_title": "অফিস লগআউট কিওস্ক",
        "kiosk_desc": "উচ্চ নিরাপত্তার জন্য, অফিস থেকে লগআউট করতে আপনাকে অবশ্যই আপনার পরিচয় কিউআর স্ক্যান করতে হবে এবং আপনার মুখ যাচাই করতে হবে।",
        "kiosk_scan": "পরিচয় কিউআর স্ক্যান করুন",
        "kiosk_cancel": "পিছনে",
        "employee_details": "কর্মীর বিবরণ",
        "name": "নাম:",
        "emp_id": "কর্মী আইডি:",
        "dept": "বিভাগ:",
        "login_time": "লগইন সময়:",
        "current_time": "বর্তমান সময়:",
        "working_hours": "কাজের সময়:",
        "proceed_face": "ফেস ভেরিফিকেশনে এগিয়ে যান",
        "verifying": "যাচাই করা হচ্ছে...",
        "admin_title": "অ্যাডমিন কন্ট্রোল প্যানেল",
        "admin_subtitle": "সমস্ত কর্মচারীদের জন্য গ্লোবাল কোম্পানি সেটিংস কনফিগার করুন",
        "logged_in_as": "লগ ইন আছেন:",
        "tab_settings": "কোম্পানি সেটিংস",
        "office_hours": "অফিসের কাজের সময়",
        "office_hours_desc": "এটি সমস্ত কর্মচারীদের জন্য বাধ্যতামূলক কাজের সময় নির্ধারণ করে। লগআউট কিওস্ক কর্মচারীদের এই সময়গুলি সম্পূর্ণ করার আগে চলে যেতে বাধা দেবে।",
        "hours_day": "প্রতি দিন ঘন্টা",
        "hours_week": "প্রতি সপ্তাহ ঘন্টা",
        "hours_month": "প্রতি মাস ঘন্টা",
        "hours_year": "প্রতি বছর ঘন্টা",
        "weekly_off": "সাপ্তাহিক ছুটির দিন",
        "save_settings": "সেটিংস সংরক্ষণ করুন",
        "dashboard": "ড্যাশবোর্ড",
        "locations": "অবস্থান",
        "admin": "অ্যাডমিন প্যানেল",
        "attendance": "উপস্থিতি সিস্টেম",
        "kiosk": "লগআউট কিওস্ক",
        "login": "লগইন",
        "register": "নিবন্ধন",
        "logout": "লগআউট",
        "settings": "সেটিংস",
        "profile": "প্রোফাইল",
        "language": "ভাষা",
        "home_badge": "এআই ফেস রিকগনিশন দ্বারা চালিত",
        "home_title": "নিরাপদ প্রমাণীকরণ",
        "home_subtitle": "ফেস রিকগনিশনের সাথে",
        "home_desc": "উন্নত এআই-চালিত ফেস রিকগনিশনের সাথে একটি ঐতিহ্যবাহী পাসওয়ার্ড সুরক্ষা সিস্টেম।",
        "home_get_started": "শুরু করুন",
        "home_sign_in": "সাইন ইন"
    },
    "mr": {
        "feature1_title": "मल्टी-अँगल फेस कॅप्चर",
        "feature1_desc": "अचूक, सुरक्षित ओळखीसाठी आपला चेहरा ४ कोनांमधून नोंदणी करा जो कोणत्याही स्थितीतून काम करतो.",
        "feature2_title": "लिव्हनेस डिटेक्शन",
        "feature2_desc": "अँटी-स्पूफिंग तंत्रज्ञान फोटो आणि व्हिडिओ शोधते, हे सुनिश्चित करते की केवळ वास्तविक व्यक्तीच प्रमाणित करू शकतात.",
        "feature3_title": "एनक्रिप्टेड एम्बेडिंग्ज",
        "feature3_desc": "चेहऱ्याचा डेटा एनक्रिप्टेड मॅथेमॅटिकल वेक्टर्स म्हणून संग्रहित केला जातो - कधीही प्रतिमा म्हणून नाही. डिझाइनद्वारे गोपनीयता.",
        "feature4_title": "रिअल-टाइम पडताळणी",
        "feature4_desc": "त्वरित प्रवेशासाठी ऑप्टिमाइझ्ड AI मॉडेल्सचा वापर करून फेस मॅचिंग २ सेकंदात होते.",
        "feature5_title": "JWT प्रमाणीकरण",
        "feature5_desc": "स्वयंचलित रिफ्रेश आणि सुरक्षित सत्र व्यवस्थापनासह उद्योग-मानक JSON वेब टोकन्स.",
        "feature6_title": "मोबाइल रिस्पॉन्सिव्ह",
        "feature6_desc": "फोन, टॅब्लेट आणि लॅपटॉपवर अखंडपणे कार्य करते. कॅमेरा कोणत्याही डिव्हाइसशी स्वयंचलितपणे जुळवून घेतो.",
        "attendance_title": "रिअल-टाइम उपस्थिती प्रणाली",
        "attendance_live": "थेट:",
        "attendance_in": "उपस्थिती इन",
        "attendance_out": "उपस्थिती आउट",
        "scan_in_title": "लॉगिनसाठी क्यूआर स्कॅन करा",
        "scan_out_title": "लॉगआउटसाठी क्यूआर स्कॅन करा",
        "scan_instruction": "फ्रेममध्ये क्यूआर कोड संरेखित करा",
        "close": "बंद करा",
        "logs_title": "आजचे लॉग",
        "search_placeholder": "नाव किंवा आयडीने शोधा...",
        "tab_today": "आजचे लॉग",
        "tab_consolidated": "एकत्रित",
        "tab_details": "तपशील",
        "status_in": "कार्यालयात",
        "status_out": "लॉग आउट",
        "status_absent": "गैरहजर",
        "table_name": "नाव",
        "table_id": "कर्मचारी आयडी",
        "table_dept": "विभाग",
        "table_in": "इन वेळ",
        "table_out": "आउट वेळ",
        "table_status": "स्थिती",
        "kiosk_title": "कार्यालय लॉगआउट कियोस्क",
        "kiosk_desc": "उच्च सुरक्षिततेसाठी, कार्यालयातून लॉगआउट करण्यासाठी आपण आपली ओळख क्यूआर स्कॅन करणे आणि आपला चेहरा सत्यापित करणे आवश्यक आहे.",
        "kiosk_scan": "ओळख क्यूआर स्कॅन करा",
        "kiosk_cancel": "मागे",
        "employee_details": "कर्मचारी तपशील",
        "name": "नाव:",
        "emp_id": "कर्मचारी आयडी:",
        "dept": "विभाग:",
        "login_time": "लॉगिन वेळ:",
        "current_time": "सध्याची वेळ:",
        "working_hours": "कामाचे तास:",
        "proceed_face": "फेस व्हेरिफिकेशनकडे जा",
        "verifying": "सत्यापित करत आहे...",
        "admin_title": "प्रशासन नियंत्रण कक्ष",
        "admin_subtitle": "सर्व कर्मचाऱ्यांसाठी जागतिक कंपनी सेटिंग्ज कॉन्फिगर करा",
        "logged_in_as": "लॉग इन केले आहे:",
        "tab_settings": "कंपनी सेटिंग्ज",
        "office_hours": "कार्यालयीन कामाचे तास",
        "office_hours_desc": "हे सर्व कर्मचाऱ्यांसाठी अनिवार्य कामाचे तास निश्चित करते. हे तास पूर्ण करण्यापूर्वी लॉगआउट कियोस्क कर्मचाऱ्यांना जाण्यापासून रोखेल.",
        "hours_day": "तास प्रति दिवस",
        "hours_week": "तास प्रति आठवडा",
        "hours_month": "तास प्रति महिना",
        "hours_year": "तास प्रति वर्ष",
        "weekly_off": "साप्ताहिक सुट्टीचा दिवस",
        "save_settings": "सेटिंग्ज जतन करा",
        "dashboard": "डॅशबोर्ड",
        "locations": "स्थाने",
        "admin": "प्रशासन पॅनेल",
        "attendance": "उपस्थिती प्रणाली",
        "kiosk": "लॉगआउट कियोस्क",
        "login": "लॉगिन",
        "register": "नोंदणी",
        "logout": "लॉगआउट",
        "settings": "सेटिंग्ज",
        "profile": "प्रोफाइल",
        "language": "भाषा",
        "home_badge": "AI चेहरा ओळख तंत्रज्ञान",
        "home_title": "सुरक्षित प्रमाणीकरण",
        "home_subtitle": "चेहरा ओळखीसह",
        "home_desc": "अ प्रगत प्रमाणीकरण प्रणाली जी पारंपारिक पासवर्ड सुरक्षा आणि AI चेहरा ओळख तंत्रज्ञान एकत्र करते.",
        "home_get_started": "सुरू करा",
        "home_sign_in": "साइन इन"
    },
    "te": {
        "feature1_title": "మల్టీ-యాంగిల్ ఫేస్ క్యాప్చర్",
        "feature1_desc": "కచ్చితమైన, సురక్షితమైన గుర్తింపు కోసం ఏ స్థానం నుండైనా పనిచేసేలా 4 కోణాల నుండి మీ ముఖాన్ని నమోదు చేయండి.",
        "feature2_title": "లైవ్‌నెస్ డిటెక్షన్",
        "feature2_desc": "యాంటీ-స్పూఫింగ్ టెక్నాలజీ ఫోటోలు మరియు వీడియోలను గుర్తిస్తుంది, నిజమైన వ్యక్తులు మాత్రమే ప్రామాణీకరించగలరని నిర్ధారిస్తుంది.",
        "feature3_title": "ఎన్‌క్రిప్టెడ్ ఎంబెడింగ్స్",
        "feature3_desc": "ముఖ డేటా ఎన్‌క్రిప్ట్ చేయబడిన గణిత వెక్టర్స్‌గా నిల్వ చేయబడుతుంది - ఎప్పుడూ చిత్రాలుగా కాదు. డిజైన్ ద్వారా గోప్యత.",
        "feature4_title": "రియల్-టైమ్ వెరిఫికేషన్",
        "feature4_desc": "తక్షణ ప్రాప్యత కోసం ఆప్టిమైజ్ చేయబడిన AI మోడల్‌లను ఉపయోగించి ఫేస్ మ్యాచింగ్ 2 సెకన్లలో జరుగుతుంది.",
        "feature5_title": "JWT ఆథెంటికేషన్",
        "feature5_desc": "ఆటోమేటిక్ రిఫ్రెష్ మరియు సురక్షిత సెషన్ మేనేజ్‌మెంట్‌తో పరిశ్రమ-ప్రమాణ JSON వెబ్ టోకెన్‌లు.",
        "feature6_title": "మొబైల్ రెస్పాన్సివ్",
        "feature6_desc": "ఫోన్‌లు, టాబ్లెట్‌లు మరియు ల్యాప్‌టాప్‌లలో సజావుగా పనిచేస్తుంది. కెమెరా ఏ పరికరానికైనా స్వయంచాలకంగా అనుకూలిస్తుంది.",
        "attendance_title": "రియల్-టైమ్ హాజరు వ్యవస్థ",
        "attendance_live": "లైవ్:",
        "attendance_in": "హాజరు ఇన్",
        "attendance_out": "హాజరు అవుట్",
        "scan_in_title": "లాగిన్ చేయడానికి QR స్కాన్ చేయండి",
        "scan_out_title": "లాగౌట్ చేయడానికి QR స్కాన్ చేయండి",
        "scan_instruction": "ఫ్రేమ్‌లో QR కోడ్‌ను సమలేఖనం చేయండి",
        "close": "మూసివేయి",
        "logs_title": "నేటి లాగ్‌లు",
        "search_placeholder": "పేరు లేదా ID ద్వారా శోధించండి...",
        "tab_today": "నేటి లాగ్‌లు",
        "tab_consolidated": "కన్సాలిడేటెడ్",
        "tab_details": "వివరాలు",
        "status_in": "ఆఫీసులో",
        "status_out": "లాగౌట్ చేయబడింది",
        "status_absent": "హాజరుకాలేదు",
        "table_name": "పేరు",
        "table_id": "ఉద్యోగి ID",
        "table_dept": "విభాగం",
        "table_in": "ఇన్ సమయం",
        "table_out": "అవుట్ సమయం",
        "table_status": "స్థితి",
        "kiosk_title": "ఆఫీస్ లాగౌట్ కియోస్క్",
        "kiosk_desc": "అధిక భద్రత కోసం, ఆఫీసు నుండి లాగౌట్ చేయడానికి మీరు మీ గుర్తింపు QR ను స్కాన్ చేసి, మీ ముఖాన్ని ధృవీకరించాలి.",
        "kiosk_scan": "గుర్తింపు QR స్కాన్ చేయండి",
        "kiosk_cancel": "వెనుకకు",
        "employee_details": "ఉద్యోగి వివరాలు",
        "name": "పేరు:",
        "emp_id": "ఉద్యోగి ID:",
        "dept": "విభాగం:",
        "login_time": "లాగిన్ సమయం:",
        "current_time": "ప్రస్తుత సమయం:",
        "working_hours": "పని గంటలు:",
        "proceed_face": "ఫేస్ వెరిఫికేషన్‌కు కొనసాగండి",
        "verifying": "ధృవీకరిస్తోంది...",
        "admin_title": "అడ్మిన్ కంట్రోల్ ప్యానెల్",
        "admin_subtitle": "ఉద్యోగులందరికీ గ్లోబల్ కంపెనీ సెట్టింగ్‌లను కాన్ఫిగర్ చేయండి",
        "logged_in_as": "లాగిన్ అయిన వారు:",
        "tab_settings": "కంపెనీ సెట్టింగ్‌లు",
        "office_hours": "ఆఫీస్ పని గంటలు",
        "office_hours_desc": "ఇది ఉద్యోగులందరికీ తప్పనిసరి పని గంటలను సెట్ చేస్తుంది. లాగౌట్ కియోస్క్ ఈ గంటలు పూర్తి చేయడానికి ముందు ఉద్యోగులను బయటకు వెళ్లకుండా నిరోధిస్తుంది.",
        "hours_day": "రోజుకు గంటలు",
        "hours_week": "వారానికి గంటలు",
        "hours_month": "నెలకు గంటలు",
        "hours_year": "సంవత్సరానికి గంటలు",
        "weekly_off": "వీక్లీ ఆఫ్ డే",
        "save_settings": "సెట్టింగ్‌లను సేవ్ చేయండి",
        "dashboard": "డాష్‌బోర్డ్",
        "locations": "స్థానాలు",
        "admin": "అడ్మిన్ ప్యానెల్",
        "attendance": "హాజరు వ్యవస్థ",
        "kiosk": "లాగౌట్ కియోస్క్",
        "login": "లాగిన్",
        "register": "నమోదు",
        "logout": "లాగ్ అవుట్",
        "settings": "సెట్టింగ్‌లు",
        "profile": "ప్రొఫైల్",
        "language": "భాష",
        "home_badge": "AI ఫేస్ రికగ్నిషన్",
        "home_title": "సురక్షిత ప్రామాణీకరణ",
        "home_subtitle": "ఫేస్ రికగ్నిషన్‌తో",
        "home_desc": "సంప్రదాయ పాస్‌వర్డ్ భద్రతను అధునాతన AI-ఆధారిత ముఖ గుర్తింపుతో మిళితం చేసే ప్రామాణీకరణ వ్యవస్థ.",
        "home_get_started": "ప్రారంభించండి",
        "home_sign_in": "సైన్ ఇన్"
    }
}

code = """import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// Helper to convert English numerals to native numerals
const numberFormatMap = {
  en: (num) => String(num),
  kn: (num) => String(num).replace(/\\d/g, d => '೦೧೨೩೪೫೬೭೮೯'[d]),
  hi: (num) => String(num).replace(/\\d/g, d => '०१२३४५६७८९'[d]),
  bn: (num) => String(num).replace(/\\d/g, d => '০১২৩৪৫৬৭৮৯'[d]),
  mr: (num) => String(num).replace(/\\d/g, d => '०१२३४५६७८९'[d]),
  te: (num) => String(num).replace(/\\d/g, d => '౦౧౨౩౪౫౬౭౮౯'[d]),
};

const resources = """ + json.dumps({k: {"translation": v} for k, v in translations.items()}, ensure_ascii=False, indent=2) + """;

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
      format: (value, format, lng) => {
        if (format === 'number') {
          const mapFunc = numberFormatMap[lng.substring(0,2)] || numberFormatMap.en;
          return mapFunc(value);
        }
        return value;
      }
    }
  });

export default i18n;
"""

with open("d:/Intern/face-auth/frontend/src/i18n.js", "w", encoding="utf-8") as f:
    f.write(code)
